device: 910B
NANOCHAT_BASE_DIR: /docker/ldeng/.cache/nanochat-ascend
NANOCHAT_BASE_DATA_DIR: /docker/ldeng/dataset/fineweb-edu-100b-shuffle-sample # sample for fast testing
#NANOCHAT_BASE_DATA_DIR: /docker/ldeng/dataset/fineweb-edu-100b-shuffle # full dataset
NANOCHAT_ENFORCE_EAGER: "1" # disable torch.compile (torchair not stable on 910B)
