device: cpu
NANOCHAT_BASE_DIR: /home/leo/.cache/nanochat-ascend
NANOCHAT_BASE_DATA_DIR: /home/leo/dataset/fineweb-edu-100b-shuffle-sample # sample for fast testing
#NANOCHAT_BASE_DATA_DIR: /home/leo/dataset/fineweb-edu-100b-shuffle # full dataset
NANOCHAT_ENFORCE_EAGER: "1" # disable torch.compile
